fix: mitigate exit code 141 when running update EEA workflow
Signed-off-by: sebthom <sebthom@users.noreply.github.com>

diff --git a/.github/workflows/update-eea-files.yml b/.github/workflows/update-eea-files.yml
--- a/.github/workflows/update-eea-files.yml
+++ b/.github/workflows/update-eea-files.yml
@@ -102,7 +102,7 @@ jobs:
           clean verify \
           -Deea-generator.action=generate
 
-        updates=$(git -C . ls-files -o -m -d --exclude-standard | head -n 50)
+        updates=$(git -C . ls-files -o -m -d --exclude-standard | head -n 50 || true)  # "|| true" is to mitgate exit code 141
 
         if [[ -z $updates ]]; then
           echo "updates=" >> "$GITHUB_OUTPUT"
